apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 50m
  install:
    createNamespace: true
    crds: CreateReplace
  chart:
    spec:
      chart: metallb
      version: "0.15.2"  # specify desired chart version
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb-system
  valuesFrom:
    - kind: ConfigMap
      name: metallb-values

