apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: copyparty

namePrefix:
  zion-

metadata:  
  name: copyparty
  namespace: copyparty

resources:
  - ../../../base/copyparty
  - certificate.yaml
  - ingress.yaml
  - middleware.yaml
