apiVersion: v1
kind: ConfigMap
metadata:
  name: xupa-db-init
data:
  init.sql: |
    -- RAID 9.3 Database Initialization
    -- Only keycloak DB + btree_gin extension.
    -- RAFM and Page Manager users/schemas/roles are created by wpkg
    -- (create-instance) with DbCreateUsers=true in Helm values.

    -- Keycloak
    CREATE USER keycloak WITH PASSWORD 'keycloak';
    CREATE DATABASE keycloak OWNER keycloak ENCODING 'UTF8';

    -- Extensions
    CREATE EXTENSION btree_gin;
