apiVersion: v1
kind: Service
metadata:
  name: homeassistant
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: homeassistant
  ports:
  - name: immich-ui
    protocol: TCP
    port: 80
    targetPort: 8123
