apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

namePrefix:
  zion-

metadata:  
  name: traefik
  namespace: traefik

resources:
  - service-account.yaml
  - rbac.yaml
  - ../../../base/traefik

patches:
  - path: patch-replicas.yaml
    target:
      kind: Deployment
