apiVersion: apps/v1
kind: Deployment
metadata:  
  name: traefik
  namespace: traefik
spec:
  replicas: 6
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik

