apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homeassistant

namePrefix:
  zion-

metadata:  
  name: homeassistant
  namespace: homeassistant

resources:
  - ../../../base/homeassistant
  - certificate.yaml
  - ingress.yaml
  - middleware.yaml
