---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: gitlab-credentials
  namespace: gitlab
spec:
  encryptedData:
    rootPassword: AgAML2EoIpLf8KDom79SrhUjOYEvKcF6TXdkMaErNSC2Wl/oB+5JrdIWmNwEpXa2IWHQ7IPGuEEih0u1wSn6Bq0zKgiUnYQ+9MWWgpNGKROp32qXGvCrFQ7cBwnTluj/VdZbP+bcVPCGflSP82qqv9ojHdeYxR+vM+DTQCDQHjRok4C/+C4rOF9DxOnsR8hca3UKc81p28QqMnkmlG3laoiGQaQs8hXxx4Zc69AJL9YrbxK9WZdEu+UDiKpEp2VZL8MjrRYBKbjkfNWq0kUMPBQlBufpd65YPanYhtoe9LNHqQjNVeAhzSVGuuA0RQPilbKaFYQgALi1qJZWbOLm+LhRcTyQDyk8Ykho9JLB3wRKvpIGQ0urZr75K4uJI+bumwjy4cVhLEqgegSzmpTRWqDx7ohJ5AyM3HgEs7aJ1bMIl646QwSf2B9Wz5/FUpRXeYZT46yz9ywg8NRKlUcGFkO55ooT/Cz1dRj7/vvMmQydx2rFC/N0aqIUy+jX/Lb0bv+aMotqsLwHEbg6SwDpQ0vET+D6+zxXOcK4fykXI+WuHmyughlLncZAuaVzvl57KirFuozLoA+Om7IcAxM1QVUztaom+HmUFhTyUBayCY3P33/cqpA15bwg2mgwFefC5hweZojyebNFmCFUSIzqWafuuw4Epdc3VdmI1sxAiyhFuBK1Eyysz8iWN9774JxidUeUT8xqMVH0j42c5KI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: gitlab-credentials
      namespace: gitlab
    type: Opaque
