apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitlab
  namespace: gitlab
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`gitlab.milanchis.com`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: zion-gitlab
          port: 80
      middlewares:
        - name: zion-gitlab-auth-middleware
  tls:
    secretName: gitlab-certificate-secret
