apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitlab

namePrefix:
  zion-

metadata:  
  name: gitlab
  namespace: gitlab

resources:
  - ../../../base/gitlab
  - certificate.yaml
  - ingress.yaml
  - middleware.yaml
  - gitlab-sealedsecret.yaml

patches:
  - path: patch-replicas.yaml
    target:
      kind: Deployment
