apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gitlab-auth-middleware
  namespace: gitlab
spec:
  forwardAuth:
    # This address should point to the cluster endpoint provided by the kubernetes service, not the Ingress.
    address: http://auth-traefik-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/traefik
    trustForwardHeader: true
    authResponseHeaders:
        - X-authentik-username
        - X-authentik-groups
        - X-authentik-entitlements
        - X-authentik-email
        - X-authentik-name
        - X-authentik-uid
        - X-authentik-jwt
        - X-authentik-meta-jwks
        - X-authentik-meta-outpost
        - X-authentik-meta-provider
        - X-authentik-meta-app
        - X-authentik-meta-version
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gitlab-cors
  namespace: gitlab
spec:
  headers:
    accessControlAllowOriginList:
      - "https://gitlab.milanchis.com"
      - "https://authentik.milanchis.com"
    accessControlAllowMethods:
      - GET
      - OPTIONS
      - POST
      - PUT
      - DELETE
    accessControlAllowHeaders:
      - Authorization
      - Content-Type
      - X-Requested-With
      - X-authentik-*
    accessControlAllowCredentials: true
    accessControlMaxAge: 100
    customResponseHeaders:
      Content-Security-Policy: "frame-ancestors 'self' https://gitlab.milanchis.com"
      X-Frame-Options: "SAMEORIGIN"

