apiVersion: apps/v1
kind: Deployment
metadata:  
  name: gitlab
  namespace: gitlab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          env:
            - name: GITLAB_ROOT_EMAIL
              value: miguelsilva5989@gmail.com
            - name: GITLAB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zion-gitlab-credentials
                  key: rootPassword
