apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:18.0.2-ce.0
        ports:
        - containerPort: 80
        env:
        - name: GITLAB_OMNIBUS_CONFIG
          value: |
            gitlab_rails['gitlab_shell_ssh_port'] = 2424
            nginx['listen_port']  = 80
            nginx['listen_https'] = false
            # HTTPS
            letsencrypt['enable'] = false
            external_url 'https://gitlab.milanchis.com'
            gitlab_rails['gitlab_https'] = true
            gitlab_rails['gitlab_port'] = 443
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 10
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
