apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rafm-extras
  namespace: xupa
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 256Mi
