---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: regcred
  namespace: glyphforge
spec:
  encryptedData:
    .dockerconfigjson: AgCZYqTsyOd47jzGIls8KKvFO0FSBm2jjDsJloL07zbEA4Wc6EpyMCOLPl5qxHPS0blbFoE3F31BJAiMg+pCT0kRR1s8571zUWUu1pcltskQohq76Q1NrvSAr2GIRw89oXNr/3dfmeHgDSKqCmqx4X6OYhL72mKeQXt8AGdZnxmuddvuqvNrVWVr/0SLHWg48M9Y9OYmAoZO7GQHZQJXhhLoCheqMlA8TLtZiwssl1Je6nsSykix0jXf/7oUpQgkog4hVbf9NBgDs/+dl69MisDZEs4Rpnz8ts4iIxIs4hiBp9t2ma2gXfLbyqpSL5RhWEWZUAhc8DcHQ0eMV/+ZnEQjdrTr9+YervIR6aEJrgJIuXrUDk4KwkWFP0PS9veNBknhTvjtXBVm2ytvLzVpDgFX/sA+LvgDrpnoaWLZ3u34/mLK9Ql1/EtL4A1ppjD1yRRYf6qRFF2FOQHGkYEiVmaQHn7u0HmQCWZIdhVcACJ5iY1r9KrZMslKdF8n4+uQkCae7XVmLkSv26b/eEuYVwo+lQ8PqOOFFve93arAvtUK3OWEA691O2TUOoh8T0/s6w9Gkyq+YCHPejBBxgcCVcnR64AeMV1DPlRQdU9HBFcZnxGIynC0bK1l56fo3/7sNYrXRY2sOYIkR1T6Ry86nAX3nnGn/K6UQ2068QA8Xb2HFdWpmm40GmQiyl8F+DNPVmZ3+CgFdVGyxMvMZGHBMmSoW9MGiZ2WtiJaf1jlR4YAdjK6XUUgmL3o0109XfuW9uH+WFnM3dZsY0l25hQn/XR5S3poPQesUk1wSwAbdfQen7bTh2FBd5r+W14vYbet4MABkXIV3yyXZTTwAImaYO8UoHPh9Kkt4Os=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: regcred
      namespace: glyphforge
    type: kubernetes.io/dockerconfigjson
