apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: glyphforge

namePrefix: zion-

resources:
  - ../../../base/glyphforge
  - certificate.yaml
  - ingress.yaml
  - middleware.yaml
