---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-credentials
  namespace: cert-manager
spec:
  encryptedData:
    apiToken: AgAKsrAc/zFMuSwhPEV/sz/zaT7Gp2iqVMRZob5HPk089yIpClWqdIKx43NAd7tdP0IWSKLaaJay9VR/6C6gbGkHa2Rh39cLz0OR7WvWA7WivPwEu/rQdHE3RYtoczofQfE2+7MhR4a2BLEKXzrGea1oRPe11ADhNUsYK5blRMh8LIOqprhMyZ/HaUe44kgV31a/QWcUMAU4ALYkH046tQ60atpW1aDPoaAliUV7xO+35I/U6ZHlo14ht3uDYT5rzkBPMYj7KkzBEghgfCr2A7eNfygJlbpVQ2Fze6BnGrFl5K708mr4qRhYFvln4F9wx8O6MQmHpLE/WQ/LHKa4EjSPGwaI2STCTgpPRm5DFtJAfyveFd8VAq98Cmv6pEMU69Rn3lrLOK6NaLAI8fLqUKytQLAKzhI+WLUrHuUbDUJkN8wqtQh6BbJ7XgQ3lhq27V2z+mUbddDt5NaU4ay+XAijCD+H/PcMdDEIkO0f/686AFmNfhtasGqiyui9FPulk8wsb+OdAycp0RzhhlECvxydtcN32JTv2+tAoQpSQyXxprxZl7TFLm/Fuc4gqdyXQtLEH2RF53ev3uvgGdqRIMSCkqXui9jX/aq9yGIjvM+gfygiPG85VPAzP+6Mg5aHpJ7ZwijvNKaaE775BLLFZDhpANPWf0hsY1OQdbbeg3NVe+iKqJwu/H4PhA1kND6E0bOYI6j2my1q4jS5PcU6kBoj2HzKxc3SH7uaiWhBtpbMn1C1xJJq0g3E
    email: AgB0D7dGlcSm2ribBjV2pe+/UCeDRC6cuFS6am22oPGgCRfmN0yfCe5K2IWuUuj7mrU9uLEacMutz882EHtfek45ASWA6jQJFhnG2vBAAUfGHhT9QMi/4JMJQrCN+CMLLMNoAtx1vAxef01U0BqgGLroxmj739A6wSHUBMs+bdkMURQJCp5eq4MdD2JmzuhD64UIu58bcDIODWumtfVGPu3ZbIKW8yIntcc3C7RmRIKdWfFCpFo5rP/mcMWjepqDodpc4TywI3DoSkS/fRJrqqkhoaapdksutbQjfOdkGfbD111TOCp9IWsshaFuhIJG1JNCJytHY/11jqcjo+3nH9dqpyz+YhIp4js/rw6Y4PEMN+7j1XGD5cBVxTGBpaVr0ZB/c8LJNFbKnIDnWod671vGaSZmACFQfWYqO04KdIs/x8FZXaptU7yv5JH2moYU34zApF5jCayUMvMzmMo0g4ccUi0fMo4FGH89FmYw5DglinJfGTrHO8dx4MqX6IrvuUA8WOBU191YkpcKKXXOxftvNbjQpc9LdhDSmbClBjIw6+zBjHUbZSVtBGacpgcfQ9/k9rsxTJFsvoVO3xybYQROhJnUzW99dbKwL54CjXtXBBNEpzdyxpNCn4StPEzkTmwpGvHqfeMOLfZJxkKYv5LMZVJexCMAnhrnZLd7ZcSjUsAaTFa6lCu2By2WNoOH0jLzGE1XBs6x6qBHLVn2KhbjKYzl7MXzR5QS
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: cloudflare-credentials
      namespace: cert-manager
    type: Opaque
