apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: radarr

namePrefix:
  zion-

metadata:  
  name: radarr
  namespace: radarr

resources:
  - ../../../base/radarr
  - certificate.yaml
  - ingress.yaml
  - middleware.yaml
