apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: test-app
  namespace: test-app      # or your namespace, e.g. open-webui or test-app ns
  # annotations:
  #   kubernetes.io/ingress.class: "traefik"
  #   traefik.ingress.kubernetes.io/router.entrypoints: websecure
  #   traefik.ingress.kubernetes.io/router.tls: "true"
  #   traefik.ingress.kubernetes.io/router.tls.certresolver: cloudflare
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`test.milanchis.com`)
      priority: 10
      services:
        - name: zion-test-app
          port: 80
      middlewares:
        - name: test-app-middleware
          namespace: test-app
    - kind: Rule
      match: Host(`test.milanchis.com`) && PathPrefix(`/outpost.goauthentik.io/`)"
      priority: 11
      services:
        - kind: Service
          # Or, to use an external Outpost, create an ExternalName service and reference that here.
          # See https://kubernetes.io/docs/concepts/services-networking/service/#externalname
          name: zion-traefik-outpost
          port: 9000
  # ingressClassName: traefik
  # rules:
  # - host: argocd.milanchis.com   # YOUR domain/subdomain, pointed to your Traefik IP via Cloudflare A record
  #   http:
  #     paths:
  #     - path: /
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: argocd-server
  #           port:
  #             number: 80
  # tls:
  #   certResolver: cloudflare
  # - hosts:
  #   - argocd.milanchis.com