apiVersion: v1
kind: Service
metadata:
  name: prowlarr
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: prowlarr
  ports:
  - name: prowlarr-ui
    protocol: TCP
    port: 80
    targetPort: 9696
