apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nfs-csi

resources:
  - namespace.yaml
  - release.yaml
  - repository.yaml

# configMapGenerator:
#   - name: longhorn-values
#     files:
#       - values.yaml=values.yaml

# configurations:
#   - kustomizeconfig.yaml
