---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: nfs-csi
spec:
  chart:
    spec:
      chart: csi-driver-nfs
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
      version: 4.11.0
  interval: 1m0s
  # valuesFrom:
  #   - kind: ConfigMap
  #     name: traefik-values

