apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

namePrefix:
  zion-

metadata:  
  name: immich
  namespace: immich

resources:
  - ../../../base/immich
  - sealedsecret.yaml
  - configmap.yaml
  - certificate.yaml
  - ingress.yaml
  - middleware.yaml
  - pvc.yaml

patches:
  - path: patch-env.yaml
    target:
      kind: Deployment
  - path: patch-env-db.yaml
    target:
      kind: Deployment

patchesStrategicMerge:
  - patch-volumes.yaml
