apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs  # Ensure this matches the storage class of the PV
  resources:
    requests:
      storage: 2Ti
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: immich-upload-pvc
#   namespace: immich
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: longhorn
#   resources:
#     requests:
#       storage: 5Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: immich-db-pvc
#   namespace: immich
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: longhorn
#   resources:
#     requests:
#       storage: 2Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: immich-ml-cache-pvc
#   namespace: immich
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: longhorn
#   resources:
#     requests:
#       storage: 1Gi