apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: open-webui-ingressroute-certificate
  namespace: open-webui
spec:
  # Secret names are always required.
  secretName: open-webui-certificate-secret

  # Issuer references are always required.
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer

  # At least one of commonName (possibly through literalSubject), dnsNames, uris, emailAddresses, ipAddresses or otherNames is required.
  dnsNames:
    - openwebui.milanchis.com
  