apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open-webui
  annotations:
    # Traefik ingress class annotation (adjust label if needed)
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: web
    # Optionally add TLS redirect, middleware, etc.
spec:
  rules:
  - host: openwebui.milanchis.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: open-webui
            port:
              number: 80
  # Optional TLS section
  # tls:
  # - hosts:
  #   - openwebui.milanchis.com
  #   secretName: openwebui-tls-secret