---
apiVersion: v1
kind: Service
metadata:
  name: auth-traefik-outpost
  namespace: open-webui
spec:
  type: ExternalName
  externalName: auth-traefik-outpost.authentik.svc.cluster.local
  ports:
    - port: 9000
      targetPort: 9000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: open-webui
  namespace: open-webui
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`openwebui.milanchis.com`) && PathPrefix(`/outpost.goauthentik.io/`)
      kind: Rule
      priority: 15
      services:
        - name: auth-traefik-outpost
          port: 9000
    - match: Host(`openwebui.milanchis.com`) && PathPrefix(`/`)
      kind: Rule
      priority: 10
      services:
        - name: zion-open-webui
          port: 80
          sticky:
            cookie:
              name: openwebui-stickiness
              secure: true
              httpOnly: true
              sameSite: lax
      middlewares:
        - name: zion-open-webui-auth-middleware
        - name: zion-open-webui-forward-headers
        - name: zion-open-webui-auth-headers
        - name: zion-open-webui-cors-middleware

    # - match: Host(`openwebui.milanchis.com`) && PathPrefix(`/api`)
    #   kind: Rule
    #   services:
    #     - name: zion-open-webui
    #       port: 80
    #   middlewares:
    #     - name: zion-open-webui-forward-headers
    #     - name: zion-open-webui-auth-headers
    #     - name: zion-open-webui-cors-middleware
  tls:
    secretName: open-webui-certificate-secret
