apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-webui

metadata:  
  name: open-webui
  namespace: open-webui

resources:
  - configmap.yaml
  - ../../../base/open-webui
  - ingress.yaml

patches:
  - path: patch-replicas.yaml
    target:
      kind: Deployment
