---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: openwebui-credentials
  namespace: open-webui
spec:
  encryptedData:
    webuiSecret: AgC0XYqY62ZfRJT7yQShPRaZSIbqvSOaN6jsPzTyqTzshac44+EgN085852WlkmsksRsq+xMtbW7W/p1WRKRKdgblDm8PE0dLCEM80ODC2aWRFuT4S7qaZ/iD9XDYoPgyam8+moouH+O9/D/YvWD3cakLsFY2xYi/vZqZRSqnBUIO8D1Id8IjmX96pQwsQmvVHbqXSv0MC2wqkqMd5rT+h05seSR6BQEvl++TvCu2n616tMFc/uFjr9vgZjdU/A7Qk/XoVmSDGnnMCOws4vv+Qgdy+3zVpVY97Iou7iZUH39BK3yHFJ9+WKfX3FOqIfiEkR7oa5AmJJjqAm5xfuguj/H1EgCrq10Hx12DoV/r8aza5UHotTGQc858ktdVFapHRd460j02Oa4b2anJIgiHLf2pqrA5Ob3RIi/EdQn2p1bw/kcEIawJR3I7DARKYT0xLfiCb38ijDMIeo2WEqgmdiiK/zYvTzVua0kFBS0759kWzPMI8JnLNLtGYbLRG1f+GfNL7mH9RniaJ+UviJRw48JKzLjVDmnEuoBCWZtcRKks0OrISKZc/pCtCRnPWiLwjmz8qZw9XWi7+T87+ohhIQ2uY6rhZ7BD47zSJ261mVAok/JnKR57/54rqq5o3s0rBnTz5a3klTBXfNvtIJhruA1tRYS5f4iub0bFAyZ4e1IVgAgr/GAi9lEq66azOFj3nQqoZeOBtyeBJMqllhpPvFaGCmrbq2SLbMbC9Q2VIyNKrtSaCk0NQcZAgrWB/DSQ8XpdQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: openwebui-credentials
      namespace: open-webui
    type: Opaque
