---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-adapter
  namespace: monitoring
spec:
  chart:
    spec:
      chart: prometheus-adapter
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  interval: 10m
  values:
    prometheus:
      url: "http://kube-prometheus-stack-prometheus"
      port: 9090
      path: ""
    rules:
      custom:
      - seriesQuery: 'files_to_process'
        resources:
          overrides:
            namespace:
              resource: namespace
        name:
          matches: '^files_to_process$'
          as: 'files_to_process'
        metricsQuery: 'files_to_process{namespace="{{.Namespace}}",app="etl-manager"}'
