apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: intel-device-plugins-gpu

resources:
  - namespace.yaml
  - release.yaml
  - repository.yaml

configMapGenerator:
  - name: intel-gpu-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml
