---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-device-plugin
  namespace: intel-device-plugins-gpu
spec:
  chart:
    spec:
      chart: intel-device-plugins-gpu
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
      version: 0.32.1
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: intel-gpu-values

