apiVersion: apps/v1
kind: Deployment
metadata:
  name: umami
  labels:
    app: umami
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: umami
  template:
    metadata:
      labels:
        app: umami
    spec:
      containers:
        - name: umami
          image: docker.umami.is/umami-software/umami:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "postgresql://umami:umami@localhost:5432/umami"

        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: umami
            - name: POSTGRES_USER
              value: umami
            - name: POSTGRES_PASSWORD
              value: umami
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
