---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-credentials
  namespace: traefik
spec:
  encryptedData:
    apiKey: AgAhKpjTWkMF12IkdpRAnzVm9jmOCqk0wvvepSnfTskMU19oBMUtKJW5BJzwAG9vGTkKMBuyl2BdWmLiBtyLtthWi5DV7lmK99BHucxbJUnjPu8hkX29/5LRkykEeXA7dopMqTSR5QEX2ovtYIAAYqpPg0wFStPCJehW6YicC0QnuDbeoS+RhiFR77fQgpXfJfyK3qWq9lhNUNZFyrRTI17du4XAxWgqiY5E0OlLQYvxDA+YDhaZLBuPM8dwo3qEE2tfmKjPtdR6Pn/rWg/mRMyLO0pkZXWkXyhSSFiU/0YMPZSd5WHdHHZ2iXynIYFkoNbVlTXFn26WozE0qPwOfm9kXcbZzbKa6sfBM48NretaqVlK7Dzc1Lfl/WlaGmrjucRvQ8Lm6m3FusdRozsFzZmxgKsocwcudRRNs6r2yxJLmMMZEOqlzfwhxkkL+EEXI01qytwcNeIppafH6FDzRsRRVSsx3uAoFTphIUTkEFHC+l7zrcXieDI/mEXNAWQIf+WSlWSU6TszNZHfOr5eckZMJvSjE4azktZScBtAz1K/SsaWOi1fgL8DY4lxs6iY4JbRG7FveyFomM+NNEBGYYzpiIdPB9Wk8h4+0e5Ovq/gsRQLEArN4bsMYKU/RsjG9BTqOXSMgnTwRQ673kDeOxepAtCJLzn3XQKcScQ8RzBBZZGP2/JOM4TuRu+6K9RrrwLaR/xWw2+X1Ri8YIDQs3aVKBIOhejhr3jIctbdrzPRsgnkOgLH
    email: AgCKK28+vnqqbOY5cTiOJLZTq5TnNMmaZGSbKPEO5cwr6qp/qKiyJKZrsaG/FFrQ1gOCvoGy5wRIjLt1SmGndLmwi0aQc42PDUOi5fqfYnRUKussW8642ZZtgaaPTqK/7mS5QR0esewGdsrmP5Ka0BS5NP4sPJVXMB1sxRqx1SuuiULwmaZWO9UncMGaP6vPmLuxdTsGmd9254jx8bG3axpmMs1E/Ysz4wWLNBK8/VfIdv3w0S+MGQ+dIzZB3t19GIi2EeEiV4A1dvCAloUcTPOIQIohHuc5oAWK9sRhAa7ifIgQI1sTUAsDQd2DB4THyuBJnfP2RCiOMh6gvgNSrJ7YgIsIctKL5ofIaKJ0DHawE7eznyLdjQq9euqudaUWLgtDmFrbh41eUxkWBiYkDHSLClj+NaWnX2+d3j+RlXuwPY+hLmJVtsq9b+i6l/QuBe6J6y5L4C024jSSf2ctor89zthYhYO2tIybBlWw3pWTy1Vz4tHEQuXesmI/8fsNs/qfReD7NN1kgLtyEtvxxkzO8iKDFK+7EmaXQSBPk7cdJq9JCwktkssvFL4nH6kx9pD5YdQJF/tKRT6/WoznnsG2bR4HyfLe2Cd27qgVfh+ED56h7Dva/9UmnQ5iyNz4QRgOQ3LokvvAHpkkd+Z7ue7t//9AoVLWqy0Uv6xMK8LtXJHEEjQY639b/IrvKFGahZG9zcZ2gSgpykijXELyIOFgLNfEzGsyCLlf
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: cloudflare-credentials
      namespace: traefik
    type: Opaque
