apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-configmap
data:
  traefik.toml: |
    [global]
      checkNewVersion = true
      sendAnonymousUsage = true
    [entryPoints]
      [entryPoints.web]
      address = ":80"

      [entryPoints.websecure]
      address = ":443"

    [providers.kubernetesCRD]

    [certificatesResolvers.cloudflare.acme]
      email = "miguelsilva5989@gmail.com"
      storage = "/ssl-certs/acme.json"
      [certificatesResolvers.cloudflare.acme.dnsChallenge]
      provider = "cloudflare"
      delayBeforeCheck = 0
