apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 2
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
      - name: traefik
        image: traefik:v3.4
        args:
          - "--configfile=/etc/traefik/traefik.toml"
        ports:
          - containerPort: 80
            name: web
          - containerPort: 443
            name: websecure
        volumeMounts:
          - name: config
            mountPath: /etc/traefik
        # envFrom:
        # - configMapRef:
        #     name: traefik-configmap
        env:
          - name: CF_API_EMAIL
            valueFrom:
              secretKeyRef:
                key: email
                name: cloudflare-credentials
          - name: CF_API_KEY
            valueFrom:
              secretKeyRef:
                key: apiKey
                name: cloudflare-credentials
      volumes:
        - name: config
          configMap:
            name: traefik-config