apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - namespace.yaml
  - sealedsecret-cloudflare.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - middleware.yaml

# configMapGenerator:
#   - name: traefik-values
#     files:
#       - values.yaml=values.yaml

# configurations:
#   - kustomizeconfig.yaml
