---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-credentials
  namespace: authentik
spec:
  encryptedData:
    authentikSecret: AgCv2SMCDMG0Ntil0kxURX62ZU4y/lKaAhYptFVpfWdH7UizbHbPldm5fKgcQlWOzesqhABRv9zAXQJBVyh9HMnpmbqgQpEA2okUsKl/B4vA9CZMWDkPt/HaqLOUBa/9OEmbsODesT7y1tZGfTq1INdHVJAzKzRcS3gxV8SnDUAAiB7spHXFHSpsJg3PgD+dJE4CAkOfT9KQrcr4MPF/S6f1CaKs2FxCRri54t/3gNl6tQTKnEM7gjL615AziMu/vw4ryQRgmybPOnbraBy4EjGClhZ8MzdsHB+2yVRH86qV16FoyuXdhtKewCWK5nNGYxOTXv9J2rKP0k8msc4Ow7qMNQJtTEVAl373MwkwSdqHHSpcWmMNdWSrq7qqkzROZBykGa4LS5k/Q3TDJ4HUzzTg+U2mID1pX2vTmsm5ZlZiUePdpNmGRdSJ/F+npHbaQ+qbUgX/rQ03Z1sluIB8TrP5b59D/67XPm9b99UZzVIql5Uo6I1YQIM5bEH+pP75WqOqyVa2Tdhfn4b14Zs3PsFoJsJ7SmUIToL2UxUCBWq8IjdBL6zF/MAhPCoCiWrQ/IEMZ8QZ9aUuNFyxl8Sut6LEY4Nw3sood22WMm/gukIoJW4xX+v/ab3qaRkudNnZytNwEG0AOTOUveoJibU2OnedhsuakYsTUvwqY+oq0Ge6hVPnncxpJaVbMaowkqDgpuxtdsFFyzj5PdhIqbnee1P5/Gi5mCCsqsqWCUB8vZHtcd4OHGepMIPer0a9fy6g09s3phUi7ip+Gys0lIq1OEzzBPkSt7ThhTUUuiD9D4QLEw==
    password: AgCBbGCiZw3/n/DPIWuoC1LMduwKVifhS63DqAfJ7Kxq6ESgelkKpPq8CeuT2dCnMTop8ksCQsz6sm47fmrNw4uIWNeWjP4BA9ZONk3BYLvNBuL3T4/81Pl0uJ/GyMKNme1iSx1Hc/hcsY24+L3/Ai0BqZfhlNmm3Hst23KcsPYeM/MikQe7O6VF0yGKenMIAc01iWe6IVchxWera6HYbDaCKLSpf+15XdAZC2MHz8VtU3QBXzW6HAjv3I5l0WEa6LGVj2hXi2VGsfA4HLWit3IVKh8o8T0/awGY65MxjqvKt1Lv33nd7OcMjGBlFsJ2Ktn150uKdLxvrDdBcpcXyJoo+07mr6QCGoe9QWDY7JkfGSmV7HdbnEqKJsKqBTnzIR0Y4c3WXRZduwihorZw/K15BIhcXKuiQLRtJUdiHEYxI7qOKgI642n73EoPXJRxDB6nv6At+U/c/tGpeXAb2w20x8BrhAnjO5z/rizFqIPbuo3vAdsFvc+YmMNNC3riZQOV321naePvAAb1QZejVsSroxBcwAeTVP31ZJu6M4/wVglc4iI5KCTLjUfiWIVw3D9ZBH6voOCOAzNJqdUAOZ2kI1AIdM64T2iKKZW4LGmz7tjOYgDBfG2A9Ir8WoHoSW1+pyJ4xcKLBSRuYLSiiFVW3sLUVL+SmXbd9WpisSCviDecojfeDzTon1HU1mmMsiO8IoH//uyhCkyFYusf+8tkZSLTJnPeMTW2SRAgQPIwfWwNzCgQXIOcZhRrk3xogWQJuA==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-credentials
      namespace: authentik
    type: Opaque
