---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: authentik-credentials
  namespace: authentik
spec:
  encryptedData:
    authentikSecret: AgBYZqgG2qX8koDY9hpVXUuDoZAOweOvFwmCxx/XLQ2Ri+Sz7iXXbwR/4VNVx42fLbWdsd8kJbBeQUTDK844i/j6oB6CAwiIYLjeueoNJwYCg/g54fFekQL+jSzfNAxQ9Ox9LQNrdbP0/LzZvGWQ/xheqjb3jMJSWEP65F2Uzxl6ijN/ML/slcZn21gJV8IhN5PDCLLDK7z7p4R7s+aWZAhQp2eg8eWAoIclp/cbiS1A4RZmrAeEw4Q7N9rAsz4H0E1gy/qUDgwVr2YxEgEJfhDYYKbulkTQsLpW3YZZKntRWg7g0EvVCPuuoVeoaguaguxPg8WLNG7oQAOAulIXk7BMRPdogMZZHSL0fgzfYvqIZGKkou3Uk5UryeQrybldP1iduMqPLinr/zFp7jldfai4iebUFaFq+JBYBQcl49GR3jYMSj7be5xZBTEfu2JhX8K8aY4wQTIHqTfKcD2jwexJS9SHMHjpmnDIb5req41z3LwfmOWXL/YSg5Vm1kWgaYXHP2MnrNNxnuzBFeAjOECEjGuBUL7jF5UQ7Lzy70hLdoRG0DD2VKSgkA0Gpec/jzKrmJccHdT/XYMRJh8OvfkqAmbnMwk9bCJ9ilRur/lrFxy/84ZvbmdvqOf5QqlH51cpucufxPZFJgDJD90BEDZCqct35Uqzj6Yf1xo5h4Yl7jwGxm5xc9DzgWHuM3PGAaVailk7Oe3Pwbb4RqLKmfOhi0o2dzrthsoBsf2CPbBynlEAEaHaSSwtsEYGaX4CDa0ZSxdsuWG/eA+kKFvH2DkdfQpLqJyVlBJJXWdWC/f26w==
    password: AgCiF+d91vs9e2e8FqyphrXV2xVjpL0KvqM0UVB+sCkdMxJZafI14o2+Z7M6RNDQIViGmsXKJNhIFP2Kkf2x8siJM62esDr1ZHHs0Iwvx4WmRuXkNgFAUV9GJulvVvoLDx/ffdQ2XkwTS9KakYsreUn8qFnGQVHYbk3OvjcpSuE/Ye+Sqtl/9/JuI/n1LvpPgmBK1hVuHoKYvTPK1PYF3YqDZQ1j69v6dXS8zXQmZQlCZsftTlxe74oSp9mR60PnKWMMWrLXJFH+yZJ91QiAhpEs3MIHq2MBCB82gr/VDYw5j3OxrimH7TNgpB8c1NUVq5+OGA/jCnvukBBfWpXk3I/GC1RqLYEgs1lSNNDgPO64jWbWaoyF6JLrc0umPdAzOlpDFAwtSaunh/AWXdxhDiIYNFdtLdL1oz06+fTuoJKNbl0NdSELpQcjsGmP354a6EWRrQFjD3pqW3rJjhM1Vf6m8jNYV0wRY9+rZPBvE1ysZWvRTB45y2kTF7/1zgl6/7fm9bIB9jn9aMmElRuvGDdDMMyuWLC4oAbzEIq1yuQ/j7jIEJDqQo32H2GhskAfStqhfuP9eaPCtlhQSBJXYCv++bLAyKo5kqiI9BffPJom/lIa78cCQmqy4vw7ttzPiO4HunOS1imqOgSCUyPqhYf16jY4Cnt6WZt+XNrAi5N74oKL3u0odZOm4GIb66ciVVRCgu8VUiB5kBvFGTu2HRFhK+npP4o4sFYvrrkntfvRAw5H7EQJ+tinZ9Ben6Wy3y8hBQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: authentik-credentials
      namespace: authentik
    type: Opaque
