apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-ingressroute-certificate
  namespace: authentik
spec:
  # Secret names are always required.
  secretName: authentik-certificate-secret

  # Issuer references are always required.
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer

  # At least one of commonName (possibly through literalSubject), dnsNames, uris, emailAddresses, ipAddresses or otherNames is required.
  dnsNames:
    - authentik.milanchis.com
  