apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik

resources:
  - namespace.yaml
  - release.yaml
  - repository.yaml
  - authentik-sealedsecret.yaml
  - certificate.yaml
  - ingress.yaml
  - service.yaml
  - middleware.yaml

configMapGenerator:
  - name: authentik-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml
