apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goauthentik
  namespace: authentik
spec:
  interval: 50m
  chart:
    spec:
      chart: goauthentik
      version: "2025.6.1"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: authentik
  # valuesFrom:
  #   - kind: ConfigMap
  #     name: traefik-values

