apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 50m
  chart:
    spec:
      chart: authentik
      version: "2025.6.4"
      sourceRef:
        kind: HelmRepository
        name: goauthentik
        namespace: authentik
  valuesFrom:
    - kind: ConfigMap
      name: authentik-values

