apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 50m
  chart:
    spec:
      chart: goauthentik
      version: "1.9.0"
      sourceRef:
        kind: HelmRepository
        name: goauthentik
        namespace: authentik
  # valuesFrom:
  #   - kind: ConfigMap
  #     name: traefik-values

