apiVersion: v1
kind: Service
metadata:
  name: authentik
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: authentik
  ports:
  - name: authentik-ui
    protocol: TCP
    port: 80
    targetPort: 9000
