---
- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/miguelsilva5989

- Entertainment:
    - Jellyfin:
        - abbr: J
          href: https://jellyfin.milanchis.com
    - Crunchyroll:
        - abbr: C
          href: https://www.crunchyroll.com/watchlist

