apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      dnsConfig: # DNS resolver workaround - ndots:5 means only queries with 5 or more dots are considered "FQDN" as-is; others get the search suffix appended. - so here we setup as 1
        options:
          - name: ndots
            value: "1" # this should now work - kubectl exec -n media zion-sonarr-5cc9b67c58-89nbf -- curl -v https://skyhook.sonarr.tv
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/sonarr:4.0.15.2941-ls289 # check in https://docs.linuxserver.io/images/docker-sonarr/#usage
        ports:
          - containerPort: 8989
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
        volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: downloads-volume
              mountPath: /data/completed
              subPath: downloads
            - name: series-volume
              mountPath: /tv
              subPath: series

      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: sonarr-pvc
        - name: downloads-volume
          persistentVolumeClaim:
            claimName: downloads-pvc-sonarr
        - name: series-volume
          persistentVolumeClaim:
            claimName: series-pvc

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
