apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/sonarr:4.0.15.2941-ls289 # check in https://docs.linuxserver.io/images/docker-sonarr/#usage
        ports:
          - containerPort: 8989
        env:
          - name: PUID
            value: 1000
          - name: PGID
            value: 1000
        volumeMounts:
            - name: config-volume
              mountPath: /config
            # TODO /downloads and /tv

      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: sonarr-pvc

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
