apiVersion: v1
kind: Service
metadata:
  name: sonarr
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: sonarr
  ports:
  - name: sonarr-ui
    protocol: TCP
    port: 80
    targetPort: 8989
