apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-ui-ingressroute-certificate
  namespace: registry
spec:
  # Secret names are always required.
  secretName: registry-ui-certificate-secret

  # Issuer references are always required.
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer

  # At least one of commonName (possibly through literalSubject), dnsNames, uris, emailAddresses, ipAddresses or otherNames is required.
  dnsNames:
    - registry-ui.milanchis.com
