---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-credentials
  namespace: cert-manager
spec:
  encryptedData:
    apiToken: AgCNE3Nkk+WSgtocCHypWYTdrkF1zINaLIuPouP3CPvcZPIHQ07nSpQ1Bw7sS6SFrhZw0s4UfFTdXR8xgmJJshQL1e71GexgcdZh2YLk8Fjob1fqyOW+2Zi/K9aEvhtVz1HszMzjMfyTwY6tO0cOFXEzGzn+FChB54sZ04HLjwNNeAl8jA6gUstM22mS8sh0gmTQvN6yF2oY2qwGqSBiLEQjWxRTd6w4V20dn5zZVUZHHUzMbVS/0mWQttNsYQpDIGTzm4zywGJMn6LvXF5hMlvgGrqPiXgjVXtteZAkqDB0h74mYKwwzVLGkyTq9fyMgI+x7fbyqV9fX8tcDh/p4xUKUGwhQ0FuDjipm83inGZpiAGaqwQE83bWUVqVdsr/FCIrV6pauZYSc9OiUesCPMzHYLTESyYl4AS3gVt9r7MiY0tZCqKyN+m4N4U2BrQSysJ1NleZz9zDTKRwO/tbcQx4lQhh38D5Kwmgyv1HjjyRJBoIlGINQAXDy/MK3wjXbRc+wcNx7kxa+oj4BKhOkUKgvz2vZVxIId4n9qXFL9Sgit54bbaQ+4lOGJMFGk/OeZX0Y0zonjR8M9B/FPMmhowePg/ZHrvjHKYsL0xC7QrcxWxMwtCz7KpfmvrjzEkt8VpwkOTcnD9oZ0NGumKSv5RE6ZDOcyCxJ9qNRaXLVOvnOPRlyftiKG73ggonSOireW5YrSGExOoh+c6cPJDFAWKK6CIs4OzCCAELPgwy1YnEVxhxbC9Lf3YJ
    email: AgB2ZozTvWH8mjFSr2wYrMORiejAixomXX4gMTFT841TcI/CtBhVKXAmJ4M0VJcTjE+oS1eUHCQVDWeVAAiutuS+qB4PybM1NEDpbeX/rCvl6hsI4ij+tM91QUOWRQdh+GiDbfXO6Q/G629ZOTOWnfijA/6OAE/ISYrquoYscbim0WQ2SQ101PSA5TqCeX/poqJBhG9wjzX7Aw54f4lN1S1W1ZC051Q+S8Cwh6BXCNIgNH0oPWnB/c30mIsoWhUOkm12ar+jf3NzgzQiVrsPR5j2qj32bB4+nZr21jdi/s2EPAqXidGh+vxMPUor7Ew4AJFaP5M+3gyCkeKbeoEs71KwShuaSBSNf0By9Fm62CWdzoikr5PafS0igqvyAkRVl6EQzF+0Ez8H1Qbrx5drFXM41dpPnpVXFIoax1MnRFduvA9OL+4sC3YPeLfk7lzmGwQbyRpy6IxSY+Y26Io3zboWFvGfKgOUL29N5IDFUzcMeB85XC9KU8UComijEqeOD5eSgdGh0y9qB12bZ3UPmGXPI1+CNh8vejAjPiz/3Ma286MY1A3sj8gz7mayuBtFe3XdJQAAMCXoMHmWvyleMc6gJWkp0iyoeLfnspZaqNlkBSgnDSgDgDYgy+AWqfCzKDgbIJfDA6LtxoPwKl5WjLKD3t1gt2oStT6bd1JGndHx42f2B9BUqGsnUwqYmsznQkV7bdg//OX9pQcKfUjyq09w9/VjS/UlsrJh
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: cloudflare-credentials
      namespace: cert-manager
    type: Opaque
