apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-ingressroute-certificate
  namespace: longhorn
spec:
  # Secret names are always required.
  secretName: longhorn-certificate-secret

  # Issuer references are always required.
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer

  # At least one of commonName (possibly through literalSubject), dnsNames, uris, emailAddresses, ipAddresses or otherNames is required.
  dnsNames:
    - longhorn.milanchis.com
