apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 16Ti  # Adjust this based on your NFS capacity
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/user/prox  # The path on the NFS server
    server: 192.168.69.115  # The NFS server IP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: longhorn
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Ti  # Adjust size to your needs
