apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  interval: 50m
  install:
    createNamespace: true
  chart:
    spec:
      chart: longhorn
      version: "1.9.0"  # specify desired chart version
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
        namespace: longhorn
  # valuesFrom:
  #   - kind: ConfigMap
  #     name: traefik-values

