apiVersion: v1
kind: Secret
metadata:
  name: transmission-credentials
  namespace: media

type: Opaque
stringData:
  RENOVATE_TOKEN: 'XXX'
  # You can set RENOVATE_AUTODISCOVER to true to run Renovate on all repos you have push access to
  RENOVATE_AUTODISCOVER: 'false'
  RENOVATE_GIT_AUTHOR: 'Renovate Bot <bot@renovateapp.com>'
  RENOVATE_PLATFORM: 'github'
