apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      dnsConfig: # DNS resolver workaround - ndots:5 means only queries with 5 or more dots are considered "FQDN" as-is; others get the search suffix appended. - so here we setup as 1
        options:
          - name: ndots
            value: "1" # this should now work - kubectl exec -n media zion-sonarr-5cc9b67c58-89nbf -- curl -v https://skyhook.sonarr.tv
      containers:
      - name: registry
        image: registry:3
        ports:
          - containerPort: 5000
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: OTEL_TRACES_EXPORTER
            value: "none"
          - name: REGISTRY_AUTH
            value: htpasswd
          - name: REGISTRY_AUTH_HTPASSWD_REALM
            value: "Registry Realm"
          - name: REGISTRY_AUTH_HTPASSWD_PATH
            value: /auth/htpasswd
          - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin
            value: "[https://registry-ui.milanchis.com]"
          - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods
            value: "[HEAD,GET,OPTIONS,DELETE]"
          - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials
            value: "[true]"
          - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers
            value: "[Authorization,Accept,Cache-Control]"
          - name: REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers
            value: "[Docker-Content-Digest]"
          - name: REGISTRY_STORAGE_DELETE_ENABLED
            value: "true"
        volumeMounts:
          - name: registry-volume
            mountPath: /var/lib/registry
            subPath: registry
          - name: auth-volume
            mountPath: /auth
            readOnly: true

      volumes:
        - name: registry-volume
          persistentVolumeClaim:
            claimName: registry-pvc
        - name: auth-volume
          secret:
            secretName: zion-registry-auth-secret

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
