---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: regcred
spec:
  encryptedData:
    .dockerconfigjson: AgA/JUxgCR1HyaJhPaZZxUI0i08t5iEK21bslY3wyg/4Nc7+N0AzzpMHou8Ul95axcPiAb+gX28bXJN2FJ1qm6HeK6Wf/Tf/CX+t8l8ooqBk22sOBuNnaH/OMQkVs4PzO6+Wbu0MDfKGr46G7wOVaOqzg2rLqTNN7eAVexlGIQ3nil47vtkC/OyryydM40knTTV5yO8jT9vVWntwWbp8YsOZFeBD9TC9nf5GYcPKnQqWyIpaQ81LkakF/jC8QMRuNgBIioTD0ui8R+T01XW6X4k4NVJUdHYDIAXSbmHxTpP+S57xF8htvf2Ar3cnGoLoNJ+iBpAmPNWSyC6GB8x9gjqq8ndB4hj/ev1WQG08OJANS/NtxoSsd4MA4jhyIIuuEle8hZfvnmKxwl3ZHeiYC54+k54TvTKph1BgnY85pjye5OQQYVmVb130l7+f/bFqWCNgQo/Yodb8kMCURqBsy84TCJw+9y9b4bJTfRbogTIeCvxHCsJNRoItnOhr1H7SLjxFNGyLdZh2ulpD58rebGXQZu0moQeNnTp6x+k+UmcuGv4NQDR5O6oZVrNixkb3gBXnXPWWM0XusO5i7k6+P8Kkuy0agbIypfaak7or/DmoIxXyYDkTeqmWHYwNRST+r06JXhxCORhIN1HQ8eR0bsS7awpv8YdrrTePIupb774fC969ZwMU7PGXI1eiUKdapcQhTRgn6JaRKMMgyvS06UAhEiBxhgOCYqFfX3qKVZRsfG43Ufx3SgOcqrctBxpzwG8XyHfCAtXvl9aSIdnfqq0GjswXhhLn8vlNI4oUzFxj3WWGn+3mmlR87BE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: regcred
    type: kubernetes.io/dockerconfigjson
