---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: registry-auth-secret
  namespace: registry
spec:
  encryptedData:
    htpasswd: AgCeH5YKIPnw0VNgSycRVZV66rnvnft/7FKl54TaXM9R1H0iTLWFe7Rb0ErYIuHKDg4dX0PEF1+oXR94PVIFIWoZ4B5Jgw54Y4bk8hBmUVbON+lYIMWeK9KXAWSNie6nSrU5o4w+ZF08RM7bPTnW3cikeoOOSwOa8H0BwRqJAHQ9rwy92s0mglu1vSQDPWtqFEveTLo5MylB6QyOLxYWXZxd0VOnBMijqlKMU0flyCyB43TiHzslGM50k8adBWU4LdKMVtTFT4ddt1ohzVItdUGa6mr8+tD3WYu4rC83r/DjEMygDiCbtwq+dfB++VoTRCN9tvi/l5tjn8lssBLin4s/ZjL8Kox6Hb/gwX4zfuLFBsSTFhydKwZoDWyK6DBcHAT00ws2BnH8ucTAy18nnDsbR+Zxej/dJ08FF9TuMGbuWGcc/vrZ4D6/XdWpv72UEyblcJUDpl1NyzfFTqYABHEBDSTpdT3y+dYeZTO7xQcC3W0veXgwfNnmXyhCZtdjHoYAqUgaZpYXlwlV1TmtrnlSp0LiaTzYJBT5V+O/YxEh62okpsFWUwFxQxkKEmfklY3Sxbh4vf6mNPZxG1pFWsRuJjj6E1pFGH8k9CjlW/0Zr5yUP4B/0zP2a6oD/RPguwchYiMQU1ZNHDEJvUcYN6bUfOzYXFyq3RmlGVhrvBKElp+AO7wxbBfSYqCHbQPNRvq9g39DhFxPvNQLypSPOnuygkhVQV4dxz33fmsTEuS2b6+UdWANIFPVWJC+9RVO5ATk9yJpZFbh1bgCHG1UOy9w57s0l2wPi7a+nSuExbJYHG0CbMK1kjuD75aYWZ02SrovY7NrTRPGVf6xiNFjHzRqRbtse9qGagKreV6WFyAfJtVCuYyi
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: registry-auth-secret
      namespace: registry
