apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: registry
  ports:
  - name: registry-ui
    protocol: TCP
    port: 80
    targetPort: 5000
