---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc-nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 12Ti
  storageClassName: nfs
