apiVersion: v1
kind: Service
metadata:
  name: nextcloud
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: nextcloud
  ports:
  - name: nextcloud-ui
    protocol: TCP
    port: 443
    targetPort: 443
