apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: garajamus-certificate
  namespace: garajamus
spec:
  secretName: garajamus-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - garajamus.milanchis.com
