apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: streamsquire-relay-certificate
  namespace: streamamus
spec:
  secretName: streamsquire-relay-certificate-secret

  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer

  dnsNames:
    - relay.streamsquire.app
