---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: streamsquire-relay-cors-middleware
  namespace: streamamus
spec:
  headers:
    accessControlAllowOriginList:
      - "https://relay.streamsquire.app"
      - "https://streamsquire.app"
      - "http://localhost:5173"
      - "http://localhost:9420"
    accessControlAllowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    accessControlAllowHeaders:
      - Authorization
      - Content-Type
      - Accept
      - Cookie
    accessControlAllowCredentials: true
    accessControlMaxAge: 100
