apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      dnsConfig: # DNS resolver workaround - ndots:5 means only queries with 5 or more dots are considered "FQDN" as-is; others get the search suffix appended. - so here we setup as 1
        options:
          - name: ndots
            value: "1" # this should now work - kubectl exec -n media zion-sonarr-5cc9b67c58-89nbf -- curl -v https://skyhook.sonarr.tv
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr:5.26.2.10099-ls279 # check in https://docs.linuxserver.io/images/docker-radarr/#usage
        ports:
          - containerPort: 7878
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
        volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: downloads-volume
              mountPath: /downloads
            - name: movies-volume
              mountPath: /movies
              subPath: movies

      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: radarr-pvc
        - name: downloads-volume
          persistentVolumeClaim:
            claimName: downloads-pvc
        - name: movies-volume
          persistentVolumeClaim:
            claimName: movies-pvc

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
