apiVersion: v1
kind: Service
metadata:
  name: homepage
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: homepage
  ports:
  - name: homepage-ui
    protocol: TCP
    port: 80
    targetPort: 3000
