apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: umami

namePrefix: zion-

resources:
  - ../../../base/umami
  - certificate.yaml
  - ingress.yaml
  - middleware.yaml
  - pvc.yaml

patchesStrategicMerge:
  - patch-volumes.yaml
