apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  labels:
    app: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      dnsConfig: # DNS resolver workaround - ndots:5 means only queries with 5 or more dots are considered "FQDN" as-is; others get the search suffix appended. - so here we setup as 1
        options:
          - name: ndots
            value: "1" # this should now work - kubectl exec -n media zion-transmission-5cc9b67c58-89nbf -- curl -v https://skyhook.transmission.tv
      containers:
      - name: transmission
        image: haugene/transmission-openvpn:latest
        ports:
          - containerPort: 9091
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: OPENVPN_PROVIDER
            value: "NORDVPN"
          - name: OPENVPN_CONFIG
            value: "spain,france,portugal"
          - name: NORDVPN_COUNTRY
            value: "ES"
          - name: NORDVPN_CATEGORY
            value: "legacy_p2p"
          - name: NORDVPN_PROTOCOL
            value: "tcp"
          # - name: NORDVPN_SERVER
          #   value: "EXAMPLE.nordvpn.com"
          - name: LOCAL_NETWORK
            value: "10.42.0.0/24"
          - name: TRANSMISSION_WEB_UI
            value: "flood-for-transmission"
        volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: downloads-volume
              mountPath: /data
              subPath: downloads

      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: transmission-pvc
        - name: downloads-volume
          persistentVolumeClaim:
            claimName: downloads-pvc-transmission

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
