apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  labels:
    app: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      dnsConfig: # DNS resolver workaround - ndots:5 means only queries with 5 or more dots are considered "FQDN" as-is; others get the search suffix appended. - so here we setup as 1
        options:
          - name: ndots
            value: "1" # this should now work - kubectl exec -n media zion-transmission-5cc9b67c58-89nbf -- curl -v https://skyhook.transmission.tv
      containers:
      - name: transmission
        image: lscr.io/linuxserver/transmission:4.0.6-R4-LS305
        ports:
          - containerPort: 9091
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
        volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: downloads-volume
              mountPath: /downloads
              subPath: downloads

      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: transmission-pvc
        - name: downloads-volume
          persistentVolumeClaim:
            claimName: downloads-pvc-transmission

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
