apiVersion: v1
kind: Service
metadata:
  name: transmission-proxy
spec:
  type: ClusterIP
  selector:
    app: transmission
  ports:
  - name: http-proxy
    protocol: TCP
    port: 8118
    targetPort: vpn-http-proxy
