apiVersion: v1
kind: Service
metadata:
  name: transmission
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: transmission
  ports:
  - name: transmission-ui
    protocol: TCP
    port: 80
    targetPort: 9091
  # - name: torrent-port
  #   protocol: TCP
  #   port: 51413
  #   targetPort: 51413
