---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-credentials
  namespace: cert-manager
spec:
  encryptedData:
    apiToken: AgCo+HcXjg/4bhKFQMjkAMvbO2JmqSr6N2//7GmDfg0xv9aw6rNGuk8wZGVfBuxwkk5ji/Hhw92uUhoU4kdbftrLOJwq5y28yCYlyqfV1vwXAn6xvDOzsfeanhqXeI1TZ3hpIqrO04BXpYguFELbQ2j5ViO0gm4RijzSGKzB5ue5AaJxdfgudn7lCEsqWoSUSFJLYDkbkpA60okhTu1IBXEsUL91PVrHsR87+058vcqHVW3zR0UW0BTkZZsJhyny8oglXTdZYX3vpKs4YpH2NFiq2CitRNrVu7UQrSBCv3Y2tEvn4xMXsxhecZD0X6kD1JcQMwCoAs8FgsUNZQbkuhR14fi3ypYhswnukZiCkrcI5l015N5bKZ0NZ9z4uf/Se35SNMs3LVj7zuBqfT/Q7hzNBItlA7p/YzIxnNEXDLyOhefGe3f11QAeISThnnsk298qFf+MQcI8OrY41AzokfVDld6woLTizv94pxKnEnq00NrY2HKrpuNabpLKba7+ztjGY3KeW1xz/9Xo2WisieHuvfbpHPQaiQrWkteConHzZrrqqvFJ3zr5CbvkPAabK9/NBaEhpAVSrBgOxj8pz0aZznzMQO9244DyHwq29+PYfdn7vXQcxN6iVCJF0e34Yfk1xmG1SxlfAc77/ynVcdSUGLYAjHyPT1uOTy/nZEoq5IFoBr6Z+T5GPsBwD/tvapZ80Wc+iEjrpmnEd2eZaySq5LXBp+ypPBCsaMJj7VQtNHbZjGjqc3sY
    email: AgAFSpqh2Jokhu/7BwT2meSCivqhax1aZtAqKTztqi956YHVpNOzl7n+jF0BsgCNDDtflh08/r1QDZiC92YkFBGWJhBkn2OnP2LviHVpxbJfjyTjVxJzCf77YJvaMVaWzsoZ07xDbIbnFi6iqUiKr0t680+r/HGb8LvLOomY/Qu2kmkrCy1u6LzyMGUfYlbQFThRNTfJog/RNg8MF1eTE2l8+1oxHQVEYjYMTYAvLaF0wigTYJsR6BkBqtaCAbEosdop5/Ht6PQbk7xo3jBG/Ud4wr1qZGsYq3DTgzwQ0HeOFRE3t6tH2s0k3+vXwdqX0wYgRrVMglZI/iDAwIqcNb+VeUmtxgKH/KgdqPYMozh0gF+5UicUzMj7e3f0E++U4nGgBUlbKeHM0e66c1c523nhINgVoVrks1+IT0RkAMi3yCK1eMQpAPjya4G979Xe7BUdPHwqmWkCMDxleTpvhFgMFPmcPFH5P3/zTxbUnoCxCMBSB3Fzxi802oQ8hjnJbzJIQWj9ZRD1UYbdGOC9J+fQjDyfxhsuAqzDEGxqRZba87V70nzVeG9FgxIt0PmFpWgl/8YEZbIdvWz1JrOl0tVt1d7HO3F7B1+KLn0YzR5o2YrwBHG1JNDBBXvmybaBC2P/BgJp01JrM1An9LrEjuRAHC/p2/11m5HjavlAx7UzKJkYcrroqnn8MjVdAYok/dlr4gWnJhxjp5SoEg4GKtZLttjoUwDUqYz5
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: cloudflare-credentials
      namespace: cert-manager
    type: Opaque
