apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      podSecurityContext:
        runAsNonRoot: false
        fsGroup: 64710
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 64710
        runAsGroup: 64710
        supplementalGroups:
          - 109 # For /dev/dri/renderD128 access (render group)
      containers:
      - name: jellyfin
        image: lscr.io/linuxserver/jellyfin:latest
        ports:
          - containerPort: 8096
            protocol: TCP
          - containerPort: 8920
            protocol: TCP
          - containerPort: 7359
            protocol: UDP
          - containerPort: 1900
            protocol: UDP
        env:
          - name: PUID
            value: "64710"
          - name: PGID
            value: "64710"
          - name: JELLYFIN_PublishedServerUrl
            value: https://jellyfin.milanchis.com
        resources:
          requests:
            gpu.intel.com/i915: "1"
          limits:
            gpu.intel.com/i915: "1"
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          runAsUser: 64710
          runAsGroup: 64710
        volumeMounts:
          # Mount /dev/dri to access Intel GPU devices for hardware acceleration
          - name: dev-dri
            mountPath: /dev/dri/renderD128
            readOnly: true
          - name: config-volume
            mountPath: /config
          - name: series-volume
            mountPath: /tvshows
            subPath: series
          - name: movies-volume
            mountPath: /movies
            subPath: movies
          - name: run-volume
            mountPath: /run
          - name: etc-group-volume
            mountPath: /etc/group
          - name: etc-gshadow-volume
            mountPath: /etc/gshadow
      volumes:
        - name: dev-dri
          hostPath:
            path: /dev/dri/renderD128
            type: CharDevice
        - name: config-volume
          persistentVolumeClaim:
            claimName: jellyfin-pvc
        - name: series-volume
          persistentVolumeClaim:
            claimName: series-pvc-jellyfin
        - name: movies-volume
          persistentVolumeClaim:
            claimName: movies-pvc-jellyfin
        - name: run-volume
          emptyDir:
            medium: Memory
        - name: etc-group-volume
          emptyDir:
            medium: Memory
        - name: etc-gshadow-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        kubernetes.io/hostname: matrix-01
