apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      podSecurityContext:
        # runAsNonRoot: false
        # fsGroup: 1000
        # seccompProfile:
        #   type: RuntimeDefault
        # runAsUser: 1000
        # runAsGroup: 1000
        supplementalGroups:
          - 44    # video group   /dev/dri/card0
          - 993   # render group  /dev/dri/renderD128
      containers:
      - name: jellyfin
        image: lscr.io/linuxserver/jellyfin:latest
        ports:
          - containerPort: 8096
            protocol: TCP
          - containerPort: 8920
            protocol: TCP
          - containerPort: 7359
            protocol: UDP
          - containerPort: 1900
            protocol: UDP
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: JELLYFIN_PublishedServerUrl
            value: https://jellyfin.milanchis.com
        resources:
          requests:
            gpu.intel.com/i915: "1"
          limits:
            gpu.intel.com/i915: "1"
        # securityContext:
        #   privileged: false
        #   allowPrivilegeEscalation: true
        #   capabilities:
        #     add:
        #       - CHOWN
        #       - SYS_ADMIN
        #     drop:
        #       - ALL
        #   # readOnlyRootFilesystem: false
        #   # runAsNonRoot: false
        #   runAsUser: 1000
        #   runAsGroup: 1000
        volumeMounts:
          # Mount /dev/dri to access Intel GPU devices for hardware acceleration
          - name: dev-dri
            mountPath: /dev/dri
            readOnly: true
          - name: config-volume
            mountPath: /config
          - name: series-volume
            mountPath: /data/tvshows
            subPath: series
          - name: movies-volume
            mountPath: /data/movies
            subPath: movies
      volumes:
        - name: dev-dri
          hostPath:
            path: /dev/dri
            type: CharDevice
        - name: config-volume
          persistentVolumeClaim:
            claimName: jellyfin-pvc
        - name: series-volume
          persistentVolumeClaim:
            claimName: series-pvc-jellyfin
        - name: movies-volume
          persistentVolumeClaim:
            claimName: movies-pvc-jellyfin
      nodeSelector:
        kubernetes.io/hostname: matrix-01
