apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
      - name: jellyfin
        image: lscr.io/linuxserver/jellyfin:latest
        ports:
          - containerPort: 8096
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: JELLYFIN_PublishedServerUrl
            value: https://jellyfin.milanchis.com
        volumeMounts:
          # Mount /dev/dri to access Intel GPU devices for hardware acceleration
          - name: dev-dri
            mountPath: /dev/dri
            readOnly: true
          - name: config-volume
            mountPath: /config
          - name: series-volume
            mountPath: /tvshows
          - name: movies-volume
            mountPath: /movies
      volumes:
        - name: dev-dri
          hostPath:
            path: /dev/dri
            type: Directory
        - name: config-volume
          persistentVolumeClaim:
            claimName: jellyfin-pvc
        - name: series-volume
          persistentVolumeClaim:
            claimName: series-pvc-jellyfin
        - name: movies-volume
          persistentVolumeClaim:
            claimName: movies-pvc-jellyfin
      nodeSelector:
        kubernetes.io/hostname: matrix-01
