apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: jellyfin
  ports:
  - name: jellyfin-ui
    protocol: TCP
    port: 80
    targetPort: 8096
