apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 50m
  install:
    createNamespace: true
  chart:
    spec:
      chart: traefik
      version: "35.*"  # specify desired chart version
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    service:
      type: LoadBalancer
    ingressClass:
      enabled: true
      isDefaultClass: true
    ports:
      web:
        redirectTo: websecure
