deployment:
  enabled: true
  kind: DaemonSet # to run on multiple nodes
  # replicas: 3 # match with number of workers
  annotations: {}
  podAnnotations: {}
  additionalContainers: []
  initContainers: []
  # tolerations:
  #   - key: "node-role.kubernetes.io/master"
  #     operator: "Exists"
  #     effect: "NoSchedule"

# -- This example pod anti-affinity forces the scheduler to put traefik pods
# -- on nodes where no other traefik pods are scheduled.
# It should be used when hostNetwork: true to prevent port conflicts
affinity: {}
#   podAntiAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       - labelSelector:
#           matchLabels:
#             app.kubernetes.io/name: traefik
#             app.kubernetes.io/instance: traefik-traefik
#         topologyKey: kubernetes.io/hostname
# affinity:
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #         - master-01
  #         - master-02
  #         - master-03
  # podAntiAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #   - labelSelector:
  #       matchLabels:
  #         app.kubernetes.io/name: traefik
  #         app.kubernetes.io/instance: traefik-traefik
  #     topologyKey: kubernetes.io/hostname
  # podAntiAffinity:
    # requiredDuringSchedulingIgnoredDuringExecution:
    # - labelSelector:
    #     matchLabels:
    #       app.kubernetes.io/name: traefik
    #       app.kubernetes.io/instance: traefik-traefik
    #   topologyKey: kubernetes.io/hostname
    # preferredDuringSchedulingIgnoredDuringExecution:
    #   - weight: 100
    #     podAffinityTerm:
    #       labelSelector:
    #         matchLabels:
    #           app.kubernetes.io/name: traefik
    #           app.kubernetes.io/instance: traefik-traefik
    #       topologyKey: kubernetes.io/hostname

service:
  enabled: true
  type: LoadBalancer
  annotations: {}
  labels: {}
  spec:
    loadBalancerIP: 10.69.69.1 # this should be an IP in the Kube-VIP range
  loadBalancerSourceRanges: []
  externalIPs: []

ingressClass:
  enabled: true
  isDefaultClass: true

ports:
  websecure:
    port: 8443
    exposedPort: 443
    tls:
      enabled: true
      certResolver: cloudflare # name of the resolver that we set below -> certificatesResolvers: -> **cloudflare**
    transport:
      respondingTimeouts:
        readTimeout: 420
        writeTimeout: 420
        idleTimeout: 420

ingressRoute:
  dashboard:
    enabled: true

persistence:
  enabled: true
  existingClaim: ssl-certs
  # name: ssl-certs
  # size: 1Gi
  # path: /ssl-certs

env:
  - name: CF_API_EMAIL
    valueFrom:
      secretKeyRef:
        key: email
        name: cloudflare-credentials
  - name: CF_API_KEY
    valueFrom:
      secretKeyRef:
        key: apiKey
        name: cloudflare-credentials


providers:  # @schema additionalProperties: false
  kubernetesCRD:
    # -- Load Kubernetes IngressRoute provider
    enabled: true
    # -- Allows IngressRoute to reference resources in namespace other than theirs
    allowCrossNamespace: true

certificatesResolvers:
  cloudflare:
    # Enable ACME (Let's Encrypt): automatic SSL.
    acme:
      
      # Email address used for registration.
      #
      # Required
      #
      email: "miguelsilva5989@gmail.com"

      # File or key used for certificates storage.
      #
      # Required
      #
      storage: "/ssl-certs/acme-cloudflare.json"

      # Use a TLS-ALPN-01 ACME challenge.
      #
      # Optional (but recommended)
      #
      # tlsChallenge:

      # Use a HTTP-01 ACME challenge.
      #
      # Optional
      #
      # httpChallenge:

        # EntryPoint to use for the HTTP-01 challenges.
        #
        # Required
        #
        # entryPoint: web

      # Use a DNS-01 ACME challenge rather than HTTP-01 challenge.
      # Note: mandatory for wildcard certificate generation.
      #
      # Optional
      #
      dnsChallenge:

        # DNS provider used.
        #
        # Required
        #
        provider: cloudflare

        # By default, the provider will verify the TXT DNS challenge record before letting ACME verify.
        # If delayBeforeCheck is greater than zero, this check is delayed for the configured duration in seconds.
        # Useful if internal networks block external DNS queries.
        #
        # Optional
        # Default: 0
        #
        # delayBeforeCheck: 0

        # Use following DNS servers to resolve the FQDN authority.
        #
        # Optional
        # Default: empty
        #
        resolvers:
        - "1.1.1.1:53"

