---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssl-certs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/ssl-certs
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssl-certs
  namespace: traefik
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: ssl-certs # This explicitly binds the PVC to the existing PV.
  storageClassName: local-path
