---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prowlarr.milanchis.com`) && PathPrefix(`/`)
      kind: Rule
      priority: 10
      services:
        - name: zion-prowlarr
          port: 80
          sticky:
            cookie:
              name: prowlarr-stickiness
              secure: true
              httpOnly: true
              sameSite: none
      middlewares:
        - name: zion-prowlarr-auth-middleware
        # - name: zion-prowlarr-cors-middleware
    - match: Host(`prowlarr.milanchis.com`) && PathPrefix(`/outpost.goauthentik.io/`)
      kind: Rule
      priority: 15
      services:
        - name: zion-auth-traefik-outpost
          port: 9000

  tls:
    secretName: prowlarr-certificate-secret
