apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

namePrefix:
  zion-

metadata:  
  name: prowlarr
  namespace: media

resources:
  - ../../../base/prowlarr
  - certificate.yaml
  - ingress.yaml
  - middleware.yaml
