---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-credentials
  namespace: traefik
spec:
  encryptedData:
    apiKey: AgB+j3j3f5T0tHBqLLxY2poZjf0WQOcrzv3+gzChEGgMk0ZHwZxajW7PGKVj+xCgFNU4HeX3SAKsgrEnipaPcrs0vTJ0u0JH/Ulp5hj41MmbzItD0UJMmGG2pyYQpEByNde38QhZcvf1oQFqoHwv6zisIh52lk8Qea+1W2NGcVFXdJkrJP00cyYTnJ/BOnC/Ilqs0m+OSDOkDSBv4EMs0sa51XG0WV2xhzHpuVQU8El5lJH9O5mvsIvtHGM4yEboLH+JAxvmVjQV8rYEDWtAAejpQL9PIvroR9p+OyDl5euqci8JH7YxWS657bu+THjSwtskvO2pqY3000HvVjLuJd+d/YjAGXSvWtZsfd93Q3vfSFw6Q+tt2W4f1/7ua1mNVTZYXeWfu+TMdqv8+Ltf7gHkztzS9f+rhbcBaKFWX2QULoOnGl7v/Ua3yr6gKQ7TgYoWYGdUCQrKA+xEsJbNQXkouefsI9VVL06/mOZgC1PKGzfwxqVZmQeJA6dm2t29+BWmxAHE9n/+GvYeZ26bqAM8MDRRjzlrqoZGN1ZLDgKfQXuyqb3WTGl8ykxn4qh4O5+/Augv1F9mf4rbY/VGdSUsNPeHGFiqkuFlWZRPU2Jz0ye7i0RBKWvYuN5wyzZsYsKqztNjExwqdpke6ZEQZSnz5sRTXkMh4BhjfvY4gnD60vLs/qPNop+BOa8bQoKpZGF8oFm3ARKOnOSacBtB/P06ghIwCaLyvKO9YyuTAiig8YnMBhwz
    email: AgBtpMbEijVWJZ0+jpDkXeLWYB3R2zXevy+yQ696ghjCfnYKuem/NLevrs2nS3404zDe+xKQ6Zd626fzqPGd6QrRAQBDSXea5DkNwKkQky2M/4JQzsoYDOzwtxm5OuMP69O8S/sVJFOr6Z67c0sFoXT5rf6qSBSF5nOXPh1pFI3/gwWstiTcioZto+Pug3x7NtVf3RsumIGBVE3E/oWvG8wAzrZ4hJpZ1yITcsDL/FIFv2bAcXxS7F7PemMwl1TbFxl0+dbdy+Flra227RayYFoOn0GHEByVJD2RkLOagFESwjK1rBh0oabB+sEwxXJKAqj9Zq6eglb6Xv8glzbtpbRPqEbvfPFHKIqdHkZenrOGjjOglMK4z1GpJEKM1f3JLd7VbojgYlTCsvZpEB4VngY1a0p8BPldaqzh6/8esKyHNhox4tyCOvjEqeT+U4CTbj86MeH6jpxTiPLRH/8xba0+xMxTeJRY5WfLPwWD7f7YLIe2m7hgH7jiL5pdMJdEIWFgF7lLBMlF8omIY2R875imfqZcF7g83TKsk93IaVL5tJIix5gohnW4rqVl5LKTJ9KhqR4gjNvQVI/fXrdtst4scHh1Vb1fA1XIgFWu0X4DUnkj/tcM0+RMxVzkdvTYkQFAF+aOCseA2HPHLHsgRpo7FdBIH2oh9wNnBLW8Jc0kwMlC0nEW0Ora7f06hexzyZyX6KtjZl8QAMJ1iQJ/CL7+b2kLqNJa7wVA
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: cloudflare-credentials
      namespace: traefik
    type: Opaque
