apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - namespace.yaml
  - release.yaml
  - repository.yaml
  - volume.yaml
  - middleware.yaml
  - cloudflare-api-token-sealedsecret.yaml
  - cluster-issuer.yaml
  - ingress.yaml

configMapGenerator:
  - name: traefik-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml
