apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - namespace.yaml
  - release.yaml
  - repository.yaml
  # - volume.yaml
  - sealedsecret.yaml
  # - middleware.yaml
  # - ingress.yaml
  - certificate.yaml

configMapGenerator:
  - name: traefik-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml
