---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-credentials
  namespace: traefik
spec:
  encryptedData:
    apiKey: AgB+algE31Yt67Jn2sWBuS1ZdCTMQm1XcF55yKZ9W58In5hjqFTpCwANpkdJu3P0NsEQz+xT+y12CYmIpSTiACxtIjHwGswDOR4Z4DvxkDKUCEi97pneyLglyHjh/6NsEhdRiaUKDI0ZnCSM3++lM8s+wkGeAjXrNvKtN+DDFSim2Hxz3RpCsYKKgA3tcaLN+nGtlFmjgVf5v4h8jiSEO9P7wzuhTiyVDx4CE1BosQxlJKpuTMkPHPwnfLvpPUXPNaoRNzGqJtcS/3dhK73xI+fyqICzSXDpU3n8unQOErtPSlZfwCLV0bEr78wubeQsrXg8Hem/qMIELSV/i1//Xtnld+xrZ74bqbcwPNNDFJFmRn5fMQb8uAeWqGKalmBTVCBcNfx8Yl5S7iWyg8mUwQjAt/L86veOPAY55wJhcjx85WoS1/gwXJg8LbSdfEPp+BErsaF4cnJwDJdyUIEgZWnWadWzeKJK5jQgMN71gLKPGcWReTpfct/GQWwePiOjokTBddORgz5Da22Jk/gV8N+F9xoTa4fmW2UrJJrCiHHpQlwDZP/iQXYNDPJ+PcAxeC8iOjuOsM2P/NAuNBT9pmsc2jgYZxHtCG91b2gspU2hXSbRqQGF/br5WulvVrS6HkbVLggcIECY25cJgplbbbHGAa/bDQ6UZeVWZNEyoH7uAwTCXeU/UVhbAXaC05TpCRbfqlNjmxDcOxePivOWE7aUrg+kDXXPOLtCPk7j4/tcSkwQFr4X+DW5
    email: AgAtNZS+ad/9y6xAlEp4vxZJnmjtjVaauv0dgTr31HIrmiroedRPCntUc4b56XePVtkIsWhEO7Eghao6mbsMiN/rR+0rpo8X3TsbCJtH1cby4htZyQ9G+TXcSgR2TJarZWw8x7uUGntjEptwhbooKKEI9M/h2E38eWzIwunqxEs2nRATLxA5S8vXdBI3JFfmV/zD0Q52bFutsRi1ah8GoNaSYBZrzLdY7F3OS7yiEhiYaGE2226rLwalRwwA/sylVulizllGt5wiPUahL144QhIGyRxCSOIH/qENm1p7Olha6kB5WZNhlqwqBfN+o5K1yvbaT0kxaze2l5I8gW7JQ/mGv90dGFLwieeBLe1glYo1x8+4pXwGE/Iw4TxZEPsF0Ec1ZX2fCRbC24ezFZxZkEiSwXdHFl9ZNLjS9JaZecjF0jOIfTykucuqYSBusQVQNzwUkgNY3deUl56EmOchtXZf6Ni0M6zIuYFcpd1TQuMDualX6Az/9Hhr8pHbpfhbqgsApBHivn0/NL991CF6FWXgJXvqsyJqizK+SsuEELFwzGm3/JKnKEnYcSgeJG/lI6bXwJ9JZiFnv/DdApBcZad2wEje5zT9WxiHKsnIL1eGls3Zutc9addOD6LVBMCNEHTCDryxPTsXbgEyOhM9rcLQu4WS4xV41VMFVODzywEVpRdxD6UhwrWaHQ8nSa0ktg5If5WoGFjGcXw1Tfb1sJtyX8xk1X4HQ7Wk
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: cloudflare-credentials
      namespace: traefik
    type: Opaque
