---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-credentials
  namespace: traefik
spec:
  encryptedData:
    apiKey: AgC4YXRXSsKm6f/cWGScohBBxzjUjhr5SFG6i4yAMofJCsuVaYK+h8T59ETFTm+CZK/3PlKQbumxbnuHyjxJ7CAjU1lCcrOlvRXSZmDRDU4r2ERb1KGWll6OyRYJf+U9LIXIiZwLwL0e4PcUzUtuYjQd0s9GQItqxwrsiUvoM6ooxlAys4/FJRJjKu5gyh9SsRIqvmAOze/4oWypd6O+hf8G6WBEHIq9zbn8kMMpkyaHFmAnxfk1f/tuxKQ2/Jk6QgIKH+FYkpZADRlOtXl4U+1coB2wSqI658C9LGoWma9hawTloTaGrrtYxXo0I3Mu0wbYG1ZiJld3FuDmc6bFCK1XqPVMtjzDUl+5HybYidN8rkxMOjrjuTY9VTFIsPBzVo55Ilkhpl+omnMJThnms+Kzwv4v+oAqlKjbARl/X0BVabX1zvYWho4MWoYGGGN2cvSGRszw8EJ7tnFaa+VQNrZzPFQJ/+xXm6WTk1UHsjNfIJXf2uuroLLTiO2eOFTyqKVB0Fu6RpyG67piiacLaDOGxc6fSnI8VlX7zRbbIiK7WVqMdS/hydvQpq8/kH5R2CEyG46BUwp0LzTqm3rfkAZI3p1fvSYK7z2xioYoyxOlX6YWLcK0S/F/gupwkWh29B4mEXOCjdOkzbb+7Cz4krPi2WLTnE6/5FQMTpfXHuOQWSnJpiqqnaDpzqBp+PYqEfq1lTKHFAyiOc2Q6q0bD0qniHO6kE67VmiF5EmgNgXjoXrW8BDz
    email: AgAR3p6rMdXnLCFWzky/MLJ7FjtfZ07qlgGc8vjFlAGnaMOI+YPaVDPZN4Cu6ZPeVtdgEnyZszhAsQf5rAZSb7MnFsYfwd5b/m3DDrphU6pa7qvDzRgA+RsGX3Ze+pkLf4y4ylsTseVL7MbEQKD1OatayyZQFUuelGfFvqB+9PwKlq095IhRoUH/bKvNbwTJwQEU0kSJfHBbmgf9u8lbJfeu4z/kmEpfDMecsL0f6ZowEEOm0u/NmYc+gSQcN2gHBP4C4pbHL9wlIbkYxW2tldWXcAqA65O3mmJP17fJRdY1raqBPSy+x4HZBFW5bDGRX6ry0txkZWlk3pnqphrClOp/oEmEJSB6skMdSzW9cBH5Wupexulw0Qg6qKQNpePHcDok3NIRR4YpfZDuSpv/aVd+xJAiyYoQEFNcOhfsvqADv1H4yMECsTwta80z4QTgzmY7UDeIdAYjdyWmeF3NQXqP+GfToUSYLzRwuLUtu8ZyEiwsOOtXn9NT1zAf7r92FrtXBvKNtM9CNM+fkDb9DVUCacWM6pWn3VQcVx30ZM2CqHo2RwvINZVnYGjCyiskYl27uTYYv/GhlKp/pI7zvipxpEXpsd0qL6/WeMW/vcSH+EtY6TgYWcoRdSIq9LeYXFmf/Cj9Adp4+QHz2XD3NP55FItsvjL1OjRvBxCoT67ZZen73kKnVEcVp6ijv4WFqoH39QGSurqlMJSDg/vzO4Zw63DpnrTEPVUX
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-credentials
      namespace: traefik
    type: Opaque
