apiVersion: apps/v1
kind: Deployment
metadata:
  name: copyparty
  labels:
    app: copyparty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: copyparty
  template:
    metadata:
      labels:
        app: copyparty
    spec:
      containers:
      - name: copyparty
        image: copyparty/ac
        ports:
          - containerPort: 3923
        env:
          # - name: PUID
          #   value: "1000"
        volumeMounts:
          - name: config-volume
            mountPath: /cfg
            readOnly: true
          - name: data-volume
            mountPath: /cfg/copyparty

      volumes:
        - name: config-volume
          configMap:
            name: copyparty-config-file
        - name: data-volume
          persistentVolumeClaim:
            claimName: copyparty-pvc

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
