apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: copyparty

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: copyparty-config-file
    files:
      - base.conf
