---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copyparty-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copyparty-share-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 13Ti
  storageClassName: nfs
