apiVersion: v1
kind: Service
metadata:
  name: copyparty
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: copyparty
  ports:
  - name: copyparty-ui
    protocol: TCP
    port: 80
    targetPort: 3923
