apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl-worker
  labels:
    app: etl-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etl-worker
  template:
    metadata:
      labels:
        app: etl-worker
    spec:
      imagePullSecrets:
      - name: zion-regcred
      containers:
      - name: etl-worker
        image: registry.milanchis.com/etl-worker:latest
        # command: ["./worker"] # docker file has an entrypoint ["/usr/local/bin/etl-worker"]
      env:
      - name: KAFKA_BROKER
        value: "zion-kafka:9092"
