apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      securityContext:
        fsGroup: 999
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
        securityContext:
          runAsUser: 999
          runAsGroup: 999
      - name: redis-insight
        image: redis/redisinsight:latest
        ports:
        - containerPort: 5540
        env:
        - name: RI_REDIS_HOST
          value: zion-redis
        volumeMounts:
        - name: redis-insight-data
          mountPath: /data
        securityContext:
          runAsUser: 999
          runAsGroup: 999

      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
        - name: redis-insight-data
          persistentVolumeClaim:
            claimName: redis-insight-pvc
