apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl-worker
  labels:
    app: etl-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: etl-worker
  template:
    metadata:
      labels:
        app: etl-worker
    spec:
      imagePullSecrets:
      - name: zion-regcred
      containers:
      - name: etl-worker
        image: registry.milanchis.com/etl-worker:latest
        imagePullPolicy: Always
        # command: ["./worker"] # docker file has an entrypoint ["/usr/local/bin/etl-worker"]
        env:
        - name: KAFKA_BROKER
          value: "zion-kafka:9092"
        - name: SERVER_HOST
          value: "zion-etl-manager"
      - name: etl-processor
        image: registry.milanchis.com/etl-processor:latest
        imagePullPolicy: Always
        command: ["./processor", "--type", "kafka"]

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
