---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: regcred
spec:
  encryptedData:
    .dockerconfigjson: AgAJsBfm9CwrVwZtmW+DYy5WupSA7aUTtiQYBCuXIRRain9v+uEaFHQJYAyAM1gpmb+rR6sC4DLFReLIlB1k6TYUtvjZtXVaZfYS1qKCgJRET6RSDOdg2NEWgnHHqny1Bg/wygKDQXplNb32dwrcGn6ktV5dMr7g/0Wb5NKxg55/pDfAifBRR+dXWsYFcgRcHqKfeFat2D+kdgXLC7a6c95MqrmMdHh1mAg0/v1CGxGnbS4H20NxTysuisTYgvWVMlMiGce+Rospwgi3ynzBE+g9XmyRHKpETGBbp9lzqigbqrxs0XMkIlJaQnh8AtxoyGF9wpSFPo9y4fuVXFrQ7RtctzXUYAnO1IG65Hl3hhzVhRGW56Ymv2lA2Wn2uzx/KALtyVAFXT3M3A23KFkbO30QW+B0lIrnAJr8ip+9+gIAyqepBVvqssHXSv3s6u/VrW/+q6O2QWNDbV1G4e6yqNxrgHmfnEU3ZJJ14gv4ZCKb7hZscHyRKgoNxMgJ8WhdkZ3el/u2m9QheOoB9euXeiO2o5f90ldpMfXK9ZXwDTBtBVgQMewxTkMEmEucCHni3P0GTx84bxi5j9RC7PWqftp8Gu8lGev6iv22ScPMWSJHncJFPwZiBEcy9cqM2eB9WfTPMLEv2A7IOGPjAIZjKou7TtPUf0NaYQKuUyNw2rcVvMVEcgMClvRYHUfKfAyUAXYFUvqD9dXHMvsSaquReeqHvKgpZl7NKyYyNqf3KNQKsnn3cNWvl0LDBHmFH8hFzzYjAHwPuLXXHw4f5uh2StcRbzDSJbr93f4LbwOfpsWKy8f6GOnmOegchUE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: regcred
    type: kubernetes.io/dockerconfigjson
