apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
  - name: kafka-client
    protocol: TCP
    port: 9092
    targetPort: 9092
  - name: kafka-controller
    protocol: TCP
    port: 29093
    targetPort: 29093
