apiVersion: v1
kind: Service
metadata:
  name: etl-manager
spec:
  selector:
    app: etl-manager
  ports:
  - name: grpc
    protocol: TCP
    port: 50051
    targetPort: 50051
  - name: metrics
    protocol: TCP
    port: 2112
    targetPort: 2112
