apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  labels:
    app: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: open-webui-configmap
        volumeMounts:
        - mountPath: /app/backend/data
          name: open-webui-storage
      
      - name: redis
        image: redis:7.4.4-alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: open-webui-storage

      # - name: ollama
      #   image: ollama/ollama:0.9.2
      #   ports:
      #   - containerPort: 11434
      #   volumeMounts:
      #   - mountPath: /app/data
      #     name: open-webui-storage
      
      - name: litellm
        image: ghcr.io/berriai/litellm:v1.72.6-stable
        ports:
        - containerPort: 4000
        volumeMounts:
        - name: open-webui-storage
          mountPath: /app

      volumes:  
      - name: open-webui-storage 
        persistentVolumeClaim:
          claimName: open-webui-pvc

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
