apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  labels:
    app: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: open-webui-configmap
        volumeMounts:
        - mountPath: /app/backend/data
          name: open-webui-storage
          subPath: openwebui-data
      
      - name: redis
        image: redis/redis:7.4.4-alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: open-webui-storage
          subPath: redis-data

      - name: ollama
        image: ollama/ollama:0.9.2
        ports:
        - containerPort: 11434
        volumeMounts:
        - mountPath: /app/data
          name: open-webui-storage
          subPath: ollama-data

      volumes:  
      - name: open-webui-storage 
        persistentVolumeClaim:
          claimName: open-webui-pvc

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
