apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  labels:
    app: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: open-webui-configmap
        volumeMounts:
        - mountPath: /app/backend/data
          name: open-webui-storage
      
      - name: redis
        image: redis:7.4.4-alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: open-webui-storage

      # - name: ollama
      #   image: ollama/ollama:0.9.2
      #   ports:
      #   - containerPort: 11434
      #   volumeMounts:
      #   - mountPath: /app/data
      #     name: open-webui-storage
      
      - name: litellm
        image: ghcr.io/berriai/litellm:v1.72.6-stable
        ports:
        - containerPort: 4000
        volumeMounts:
        - name: litellm-config-volume
          mountPath: /app/proxy_server_config.yaml
          subPath: config.yaml
        env:
          DATABASE_URL: "postgresql://llmproxy:dbpassword9090@postgres.open-webui.svc.cluster.local:5432/litellm"
          STORE_MODEL_IN_DB: "True" # allows adding models to proxy via UI
      
      - name: postgres
        image: postgres:16
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: "litellm"
          - name: POSTGRES_USER
            value: "llmproxy"
          - name: POSTGRES_PASSWORD
            value: "dbpassword9090"
        volumeMounts:
          - name: open-webui-storage
            mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command:
              - pg_isready
              - "-d"
              - litellm
              - "-U"
              - llmproxy
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6

      volumes:  
      - name: open-webui-storage 
        persistentVolumeClaim:
          claimName: open-webui-pvc
      - name: litellm-config-volume
        configMap:
          name: litellm-config-file

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
