apiVersion: v1
kind: Service
metadata:
  name: open-webui
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: open-webui
  ports:
  - name: webui-http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: litellm-api
    protocol: TCP
    port: 4000
    targetPort: 4000