apiVersion: v1
kind: Service
metadata:
  name: open-webui
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: open-webui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  - protocol: TCP
    port: 4000 # litellm container
    targetPort: 4000 # litellm container