---
# auth-traefik-outpost - defined in radarr
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sonarr.milanchis.com`) && PathPrefix(`/`)
      kind: Rule
      priority: 10
      services:
        - name: zion-sonarr
          port: 80
          sticky:
            cookie:
              name: sonarr-stickiness
              secure: true
              httpOnly: true
              sameSite: none
      middlewares:
        - name: zion-sonarr-auth-middleware
        # - name: zion-sonarr-cors-middleware
    - match: Host(`sonarr.milanchis.com`) && PathPrefix(`/outpost.goauthentik.io/`)
      kind: Rule
      priority: 15
      services:
        - name: zion-auth-traefik-outpost
          port: 9000

  tls:
    secretName: sonarr-certificate-secret
