apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sonarr

namePrefix:
  zion-

metadata:  
  name: sonarr
  namespace: sonarr

resources:
  - ../../../base/sonarr
  - certificate.yaml
  - ingress.yaml
  - middleware.yaml
