apiVersion: v1
kind: Service
metadata:
  name: immich
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: immich
  ports:
  - name: immich-ui
    protocol: TCP
    port: 2283
    targetPort: 2283
