---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: authentik-credentials
  namespace: authentik
spec:
  encryptedData:
    authentikSecret: AgA2UTfC+awtwpc7vQEN6zep7ej9CpW4v6aYp5hTmVGyNzsixxiJN96jxW6Fh7+v7Ilg/sJDVDdUMYvSELecCwgdLslTbIMUx77qjN3NDSFDsHZTmxK1t9+X36cvmoG828CnTevvU2gM+0YW6+jRbfcjgFYEcAr7xfGTWhHeLzFKJZgPPA+xRL6ubNZxyzGQGqjerx2K3dB95jleqgVnI69v1m5CChVWXJazfmavzjAjecZEkyiQICNMNmLo7SfHJgRZAVyToqwbwdfMIQ/BjnwSAoBnardbgenkudrv/9PzSbxOjKKJSVSVlduFpikKL9FGH65akbEIAOEb8rp/12RZ6T2URnf5YrJF2W8xri/zAsCV7FPmGBI0r0NdF4rjIFxE6vK2OKymOhTnkiL3mLpPl7qqFgGZ94j+AUUvI+TKyYBIhTuQmniZ/hvyvvbeUu7TACRxqxqY/ARqel8kXpEIYRSTu0VlmThPs6JRcwtaB0M/Ccurywa1J92kDdPhpkLT3GpTWGi6CGHi5YZrAtLP/UTSh8dmQR3hsdoCRO+nZmPvwSsQQXJEb9xRajExdAiw8iH9+U6haLkJamvwU8Gbg75L73xK+z99Ipkw4t/iu2uliqbD5e7HaUcxNGvHw2GIeuNMv5NRxZjcMQiQfp8LZ4mUT+5N7aMlTOS5n6ncMYtfekTIiN86U6IQfe/bhlejEEbgbAUZ46T07otG/RdBN32hIHgta9MDuescs1pbve8uhoAQGBKrDxzFaCjQ3LInVk7VBOltkdeYCpimbV4Eb+Mfmv+PE4uZBmBo9UZdrA==
    postgresPassword: AgC6cFk5C1nm+WlIgAMUWnM05gMJl7ROom80RUvZ2Wq07eeJw8qq9KiaNQfA1mGm2n61oKvsuoXj6DofQWG/l6vBSB+bU4QTqxfRgqEQvOjAa8gAtckfwNW64892SqPZ7uMu+2UmDV+cSFFETviZt8JkV7SrVx9m1HbUitmtOMX3XgNQbOv9KrdCzSRsE4BPfgEWPYhrYbAeSA8nypGW3UMAcy+9RpNCzozVJzArHszRqNHT5bSbbq6akplEdeMVMgTxOewBguzY+TD4HP1J9E6+iBw+wsZCw44jZn5t65HdP23vVSBF26UlR0OoB4+lELjEyPeACAdWIti2/hgCugeFQrwQ0/SdCgHO/uyvcNRHrtah/veDjrJ/582D2w8RQGS2Sv2i+95DmVlXBibTO8THhBDQc264vLk3EZs8ZOeQndIIUGHl0TtlzXZC2NMwkmUif49QFXl3OqjkeZK1+MgMDqAmcQF5+dwVPmgf9jQCVnhfK9SZfDjfk/DH+0dl16lgO0NJwL3tRYr7rDzSnPA3fPliGEi6BRs9XOdO3bboWjqNjmqHm/fQg2IGgxfVdYdrbihOnkM6alXNkoiEDofFtaMacxKTgPB/3Jc4U04cqja7MQeNUrFF/6OViyLc65w7xS/HcFUwtBlaoLi3t2J/263zmcwoSN9tGjlryQXHO1qSwGT5hZAu6B54MFKYjoO0hgm4lHGKv2rDy9q9bvvL8pjrQai3JQjx7N0KpqAv68vcTZ627oGjDXHRn+ObNfnyCw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: authentik-credentials
      namespace: authentik
    type: Opaque
