apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik

resources:
  - ../../base/authentik
  - authentik-sealedsecret.yaml
  - certificate.yaml
  - ingress.yaml

configMapGenerator:
  - name: authentik-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml
